export const DISPLAY_REPORTS = [
  {
    id: 'log-1',
    module: 'LOG',
    name: 'Log Daily Inward',
    type: 'DATE',
    endpoint: '/report/download-excel-log-inward-daily-report',
  },
  {
    id: 'log-2',
    module: 'LOG',
    name: 'Item Wise Inward',
    type: 'RANGE',
    endpoint: '/report/download-excel-item-wise-inward-daily-report',
  },
  {
    id: 'log-3',
    module: 'LOG',
    name: 'Log Wise Inward',
    type: 'RANGE',
    endpoint: '/report/download-excel-log-item-wise-inward-daily-report',
  },
  {
    id: 'log-4',
    module: 'LOG',
    name: 'Item Further Process',
    type: 'RANGE',
    endpoint: '/report/download-excel-log-item-further-process-report',
  },
  {
    id: 'veneer-1',
    module: 'VENEER',
    name: 'Veneer Inward',
    type: 'RANGE',
    endpoint: '/report/download-excel-veneer-inward-report',
  },
  {
    id: 'flitch-2',
    module: 'FLITCHING FACTORY',
    name: 'Item Wise Flitch',
    type: 'RANGE',
    endpoint: '/report/download-excel-item-wise-flitch-report',
  },
  {
    id: 'flitch-3',
    module: 'FLITCHING FACTORY',
    name: 'Log Wise Flitch',
    type: 'RANGE',
    endpoint: '/report/download-excel-log-wise-flitch-report',
  },
  {
    id: 'flitch-1',
    module: 'FLITCH',
    name: 'Daily Flitch',
    type: 'DATE',
    endpoint: '/report/download-excel-flitch-daily-report',
  },
  {
    id: 'flitch-4',
    module: 'FLITCH',
    name: 'Item Further Process',
    type: 'RANGE',
    endpoint: '/report/download-excel-flitch-item-further-process-report',
  },
  {
    id: 'slicing-1',
    module: 'SLICING',
    name: 'Daily Slicing',
    type: 'DATE',
    endpoint: '/report/download-excel-slicing-daily-report',
  },
  {
    id: 'dressing-1',
    module: 'DRESSING',
    name: 'Daily Dressing',
    type: 'DATE',
    endpoint: '/report/download-excel-dressing-daily-report',
  },
  {
    id: 'dressing-2',
    module: 'DRESSING',
    name: 'Log Wise Dressing',
    type: 'RANGE',
    endpoint: '/report/download-excel-log-wise-dressing-report',
  },
  {
    id: 'dressing-3',
    module: 'DRESSING',
    name: 'Stock Register/O/C Dressing',
    type: 'RANGE',
    endpoint: '/report/download-excel-dressing-stock-register',
  },
  {
    id: 'smoking-dying-1',
    module: 'SMOKING & DYING',
    name: 'Daily Smoking & Dying',
    type: 'DATE',
    endpoint: '/report/download-excel-smoking-dying-daily-report',
  },
  {
    id: 'smoking-dying-2',
    module: 'SMOKING & DYING',
    name: 'Stock Register Smoking & Dying',
    type: 'RANGE',
    endpoint: '/report/download-excel-smoking-dying-stock-register',
  },
  {
    id: 'grouping-1',
    module: 'GROUPING',
    name: 'Daily Grouping',
    type: 'DATE',
    endpoint: '/report/download-excel-grouping-daily-report',
  },
  {
    id: 'grouping-2',
    module: 'GROUPING',
    name: 'Stock Register Grouping',
    type: 'RANGE',
    endpoint: '/report/download-excel-grouping-stock-register',
  },
  {
    id: 'grouping-3',
    module: 'GROUPING',
    name: 'Stock Register Thickness Wise Grouping',
    type: 'RANGE',
    endpoint: '/report/download-excel-grouping-stock-register-thickness-wise',
  },
  {
    id: 'grouping-4',
    module: 'GROUPING',
    name: 'Stock Register Group Wise Grouping',
    type: 'RANGE',
    endpoint: '/report/download-excel-grouping-stock-register-group-wise',
  },
  {
    id: 'face-1',
    module: 'FACE',
    name: 'Face Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-face',
  },
  {
    id: 'core-1',
    module: 'CORE',
    name: 'Core Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-core',
  },
  {
    id: 'cross-cut-1',
    module: 'CROSS CUT',
    name: 'Daily CrossCut',
    type: 'DATE',
    endpoint: '/report/download-excel-crosscutting-daily-report',
  },
  {
    id: 'cross-cut-2',
    module: 'CROSS CUT',
    name: 'Log Wise Cross Cut',
    type: 'RANGE',
    endpoint: '/report/download-excel-log-wise-crosscut-report',
  },
  {
    id: 'tapping-1',
    module: 'TAPPING',
    name: 'Splicing Details Daily Report',
    type: 'DATE',
    endpoint: '/report/download-excel-tapping-daily-report',
  },
  {
    id: 'tapping-2',
    module: 'TAPPING',
    name: 'Stock Register (Sales Name Wise)',
    type: 'RANGE',
    endpoint: '/report/download-excel-tapping-stock-register',
  },
  {
    id: 'tapping-3',
    module: 'TAPPING',
    name: 'Stock Register (Sales Name - Thickness Wise)',
    type: 'RANGE',
    endpoint: '/report/download-excel-tapping-stock-register-thickness-wise',
  },
  {
    id: 'tapping-4',
    module: 'TAPPING',
    name: 'Stock Register (Thickness Wise)',
    type: 'RANGE',
    endpoint: '/report/download-excel-tapping-item-stock-register-thickness-wise',
  },
  {
    id: 'pressing-1',
    module: 'PRESSING',
    name: 'Daily Pressing',
    type: 'DATE',
    endpoint: '/report/download-excel-pressing-daily-report',
  },
  {
    id: 'pressing-3',
    module: 'PRESSING',
    name: 'Stock Register (Sales name - Thickness - Process)',
    type: 'RANGE',
    endpoint: '/report/download-excel-pressing-stock-register-sales-thickness-process',
  },
  {
    id: 'pressing-4',
    module: 'PRESSING',
    name: 'Stock Register (Group no wise)',
    type: 'RANGE',
    endpoint: '/report/download-excel-pressing-stock-register-group-wise',
  },
  {
    id: 'pressing-5',
    module: 'PRESSING',
    name: 'Stock Register (Sales name - Thickness)',
    type: 'RANGE',
    endpoint: '/report/download-excel-pressing-stock-register-sales-thickness',
  },
  {
    id: 'peeling-1',
    module: 'PEELING',
    name: 'Daily Peeling',
    type: 'DATE',
    endpoint: '/report/download-excel-peeling-daily-report',
  },
  {
    id: 'plywood-1',
    module: 'PLYWOOD',
    name: 'Plywood Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-plywood',
  },
  {
    id: 'plywood-2',
    module: 'PLYWOOD',
    name: 'Plywood Stock By Pellet',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-plywood-by-pellet',
  },
  {
    id: 'plywood-3',
    module: 'PLYWOOD',
    name: 'Item Wise Plywood Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-plywood-item-wise',
  },
  {
    id: 'mdf-1',
    module: 'MDF',
    name: 'MDF Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-mdf',
  },
  {
    id: 'mdf-2',
    module: 'MDF',
    name: 'MDF Stock By Pellet',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-mdf-by-pellet',
  },
  {
    id: 'mdf-3',
    module: 'MDF',
    name: 'Item Wise MDF Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-mdf-item-wise',
  },
  {
    id: 'fleece-1',
    module: 'FLEECE PAPER',
    name: 'Fleece Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-fleece',
  },
  {
    id: 'fleece-2',
    module: 'FLEECE PAPER',
    name: 'Fleece Stock By Inward',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-fleece-by-inward',
  },
  {
    id: 'fleece-3',
    module: 'FLEECE PAPER',
    name: 'Item Wise Fleece Stock',
    type: 'RANGE',
    endpoint: '/report/download-stock-report-fleece-item-wise',
  },
  {
    id: 'store-1',
    module: 'OTHER GOODS',
    name: 'Other Goods Daily Report',
    type: 'DATE',
    endpoint: '/report/download-other-goods-daily-report',
  },
  {
    id: 'store-2',
    module: 'OTHER GOODS',
    name: 'Other Goods Item Report',
    type: 'RANGE',
    endpoint: '/report/download-excel-other-item-report',
  },
  {
    id: 'store-3',
    module: 'OTHER GOODS',
    name: 'Other Goods Machine Wise Report',
    type: 'RANGE',
    endpoint: '/report/download-excel-machine-wise-report',
  },
  {
    id: 'store-4',
    module: 'OTHER GOODS',
    name: 'Other Goods Consumption Report',
    type: 'RANGE',
    endpoint: '/report/download-other-goods-consumption-report',
  },
  {
    id: 'store-5',
    module: 'OTHER GOODS',
    name: 'Other Goods Inward Report',
    type: 'RANGE',
    endpoint: '/report/download-other-goods-inward-report',
  },
];

export const DISPLAY_REPORTS_MAP = new Map(
  DISPLAY_REPORTS.map((report) => [report.id, report])
);

export const getDisplayReportById = (reportId) =>
  DISPLAY_REPORTS_MAP.get(String(reportId || '').trim());
